In [7]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
import numpy as np
a1 = np.array([1, 2, 3])
a1


array([1, 2, 3])

In [3]:

type(a1)


numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])


In [5]:
a2


array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a1.shape


(3,)

In [15]:
a2.shape


(2, 3)

In [16]:
a3.shape


(2, 3, 3)

In [17]:
a1.ndim, a2.ndim, a3.ndim


(1, 2, 3)

In [18]:
a1.dtype, a2.dtype, a3.dtype


(dtype('int32'), dtype('float64'), dtype('int32'))

In [19]:
a1.size, a2.size, a3.size


(3, 6, 18)

In [22]:

type(a1), type(a2), type(a3)


(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [21]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df


0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [2]:
sample_array = np.array([1, 2, 3])
sample_array


array([1, 2, 3])

In [3]:
sample_array.dtype


dtype('int32')

In [4]:
ones = np.ones((2, 3))
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
ones.dtype


dtype('float64')

In [6]:
type(ones)


numpy.ndarray

In [7]:
zeros = np.zeros((2, 3))


In [8]:
zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array = np.arange(0, 10, 2)
range_array


array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array


array([[5, 3, 4, 8, 2],
       [6, 2, 6, 7, 4],
       [6, 8, 7, 1, 0]])

In [12]:
random_array.size

15

In [13]:
random_array.shape

(3, 5)

In [16]:
random_array_2 = np.random.random((5, 3))
random_array_2


array([[0.75883646, 0.26909542, 0.25290824],
       [0.9591016 , 0.1488868 , 0.42058789],
       [0.96712382, 0.17861359, 0.56630239],
       [0.16799062, 0.30676994, 0.8976196 ],
       [0.73843648, 0.84701066, 0.75858303]])

In [17]:
random_array_2.shape


(5, 3)

In [19]:

random_array_3 = np.random.rand(5, 3)
random_array_3


array([[0.17358779, 0.64004073, 0.97134887],
       [0.95594026, 0.76214745, 0.52323026],
       [0.14704589, 0.77858879, 0.99288234],
       [0.78075421, 0.55022802, 0.0553412 ],
       [0.27970604, 0.55375005, 0.23343757]])

In [21]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4


array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [22]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5


array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [23]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5


array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [24]:
random_array_4


array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## 3.Viewing arrays and matrices

In [25]:
np.unique(random_array_4)


array([0, 1, 3, 4, 5, 6, 8, 9])

In [26]:
a1

array([1, 2, 3])

In [29]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [2]:
a3

NameError: name 'a3' is not defined

In [31]:

a1[0]


1

In [32]:
a2.shape

(2, 3)

In [33]:
a3.shape

(2, 3, 3)

In [8]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
a1

array([1, 2, 3])

In [12]:

a2[1]


array([4. , 5. , 6.5])

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a3.shape


(2, 3, 3)

In [15]:
a3[:2, :2, :2]


array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [16]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4


array([[[[0, 7, 5, 9, 0],
         [2, 8, 6, 8, 9],
         [7, 9, 6, 2, 0],
         [8, 3, 5, 6, 3]],

        [[7, 2, 2, 5, 0],
         [0, 1, 0, 8, 5],
         [4, 5, 4, 7, 0],
         [3, 7, 1, 8, 5]],

        [[9, 7, 5, 7, 8],
         [2, 7, 8, 5, 7],
         [8, 8, 1, 2, 9],
         [0, 1, 0, 9, 4]]],


       [[[9, 5, 8, 1, 2],
         [3, 8, 3, 7, 1],
         [6, 9, 8, 7, 4],
         [9, 4, 9, 1, 6]],

        [[9, 3, 4, 5, 4],
         [3, 8, 1, 8, 9],
         [7, 1, 6, 6, 6],
         [4, 2, 1, 5, 5]],

        [[1, 2, 6, 6, 1],
         [0, 6, 4, 1, 7],
         [5, 3, 7, 3, 9],
         [3, 4, 6, 0, 5]]]])

In [17]:
a4.shape, a4.ndim


((2, 3, 4, 5), 4)

In [18]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]


array([[[[0],
         [2],
         [7],
         [8]],

        [[7],
         [0],
         [4],
         [3]],

        [[9],
         [2],
         [8],
         [0]]],


       [[[9],
         [3],
         [6],
         [9]],

        [[9],
         [3],
         [7],
         [4]],

        [[1],
         [0],
         [5],
         [3]]]])


## 4. Manipulating & comparing arrays

## Arithmetic

In [9]:
a1

array([1, 2, 3])

In [11]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [12]:
a1 + ones

array([2., 3., 4.])

In [13]:
a1 - ones

array([0., 1., 2.])

In [15]:
a1 * ones

array([1., 2., 3.])

In [16]:
a1

array([1, 2, 3])

In [17]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [18]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
# How can you reshape a2 to be compatible with a3? 
# Search: "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [21]:
a1 / ones

array([1., 2., 3.])

In [22]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [23]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [24]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [25]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [26]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [27]:
a1 + ones

array([2., 3., 4.])

In [28]:
np.add(a1, ones)

array([2., 3., 4.])

In [29]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [30]:
a1 / 2

array([0.5, 1. , 1.5])

In [19]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [32]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [7]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [6]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])